### ISSUE TITLE
Handling optimizations in generator

### ISSUE THREAD

**Issue by iliakur** [potassco/asprilo#14]
I'm trying to add some custom constraints over the instances generated automatically and these constraints include an optimization statement. Currently the generator simply selects the first model derived without making sure it has the optimal cost value.

Is there anything equivalent to `clingo`'s `--outf=1` flag available already? I can't seem to find anything currently. [the API docs](http://potassco.sourceforge.net/gringo.html#Control-__init__) say it's not supported directly, i.e. it would have to be implemented on the Python side of things.

**Comment by pobermei** [comment]
As a quick workaround, you can simply edit the solve options in the generator yourself, i.e., simply edit

https://github.com/potassco/asprilo/blob/generator/generator/generator/generator.py#L24-L27

I'll add an option to cleanly redefine those options via command line pars in the next days.

**Comment by pobermei** [comment]
I won't add official support for (arbitrary) optimization statements other than the manual way suggested above for the time being due the related performance impact in general.

Without a clear use case, I won't add  support for other instance output formats similar `--outf`.
