### ISSUE TITLE
conda installation throws errors

### ISSUE THREAD

**Issue by tortinator** [potassco/asprilo#32]
Running 'conda install asprilo-visualizer' on fedora throws errors:
-----
Collecting package metadata (current_repodata.json): done
Solving environment: - 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:
-----
UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - pip -> python[version='>=3.6,<3.7.0a0']

**Comment by tortinator** [comment]
@pobermei Hi, could you fix this before your vacation, givan that many people were interested using asprilo at ICAPS and SOCS..? Cheers -t

**Comment by peschue** [comment]
Dear both,

I had a similar problem with hexlite and its dependency on potassco /
clingo. The solution was to force the installation of a python version that
potassco / clingo supports. Conda does not do all of these resolutions by
itself, unfortunately.

Best,
Peter

--
Dr Peter SCHÜLLER
https://peterschueller.com/


Am Do., 18. Juli 2019 um 17:36 Uhr schrieb Torsten Schaub <
notifications@github.com>:

**Comment by pobermei** [comment]
@tortinator To make sure that you don't have any outdated dependencies in your current conda env, 
please try the following:

1. Create a fresh conda environment with:
```bash
conda create -n asprilo 
```
2. Activate the environment
```bash
conda activate asprilo
```
3. Install the visualizer via
```bash
 conda install asprilo-visualizer -c potassco -c potassco/label/dev  
```
The channel `-c potassco/label/dev` is needed since we rely on python 3.7 and hence clingo 5.4

**Comment by tortinator** [comment]
This seems to have worked, although I haven't restarted from scratch.
I also had to re-initialize conda wih bash - strange!
