### ISSUE TITLE
How to load a plan?

### ISSUE THREAD

**Issue by sanghoonsim** [potassco/asprilo#40]
I tried to load instnaces and it worked.

But when I try to load plan, nothing is opened.

The example of plan is below:
%plan.txt
occurs(object(robot ,1),move (-1,0),1). 
occurs(object(robot ,2),move (-1,0),1).
occurs(object(robot ,1),move (-1,0),2). 
occurs(object(robot ,2),pickup ,2).

**Comment by pobermei** [comment]
Your `occurs/3` atoms are not correctly formatted, see [here](https://github.com/potassco/asprilo/blob/develop/docs/specification.md#output-format).
