### ISSUE TITLE
Solving from the visualizer

### ISSUE THREAD

**Issue by ptal0003** [potassco/asprilo#43]
Hi
When I try to solve from the visualizer directly, I am not getting a solution although in terminal it is mentioned that solution found. All occurs atoms are not present when being passed to the solver and I am getting the following warning. 
![image](https://user-images.githubusercontent.com/62492172/147532013-7f1fa18d-a402-4eed-8f8b-ce3cf54cebe8.png)
Any help on this would be appreciated.

**Comment by pobermei** [comment]
This is the expected behavior, i.e., the visualizer only visualizes your solution (ASP facts) but does not print it to stdout.
