### ISSUE TITLE
double declared fields

### ISSUE THREAD

**Issue by tortinator** [potassco/asprilo#6]
The instance file

instances/standard_cases/4/warehouse_x10_y10_n100_r4_s12_ps3_pr3_u20_o0_N1/merged/x10_y10_n100_r4_s12_ps3_pr3_u20_o5_N10.lp

has (6,1) marked as **both** picking station and highway

**Comment by pobermei** [comment]
Fixed in 57a2ce6cbe728edd3313ef2a92c38d84b3197b76.
