### ISSUE TITLE
core dump when saving handcrafted instance

### ISSUE THREAD

**Issue by tortinator** [potassco/asprilo#7]
torsten@bono 2010:~/ASP/asprilo> visualizer 
Traceback (most recent call last):
  File "/home/torsten/local/bin/visualizer", line 338, in save_instance
    file_name = self._file_dialog.selectedFiles()[0]
IndexError: list index out of range
Aborted (core dumped)

**Comment by tortinator** [comment]
This is reprodicible from a 1x1 grid with enabled node and selecting 'save instance' in the menu

**Comment by tortinator** [comment]
The bug does **not** occur in our uni environment!

**Comment by pobermei** [comment]
I couldn't reproduce this locally nor with the current develop version in our uni environment.
This is most likely a bug of an older pyqt version that has been fixed meanwhile. Make sure that you have a pyqt version >=5.7
