### ISSUE TITLE
Undefined variable in `finally` clause

### ISSUE THREAD

**Issue by iliakur** [potassco/asprilo#9]
The finally clause [here](https://github.com/potassco/asprilo/blob/master/generator/ig.py?utf8=%E2%9C%93#L421) references a variable `igen` which is not always defined.

I haven't had time to look into how to fix this, but I'm guessing @pobermei can probably find it much quicker, being much more familiar with the code.

**Comment by pobermei** [comment]
This bug was fixed in the develop branch.
